baseURL = "https://linuxdive.com"
languageCode = "en-us"
title = "The Fun, Unexpected Side of Linux"

[params]
  siteName = "LinuxDive"
  siteDescription = "Linux Dive covers the coolest uses of Linux in business, education, gaming, and beyond. From home projects to big industry, discover the fun side of Linux."

[markup.highlight]
  codeFences = true
  lineNos = true
  style = "native"

[permalinks]
  posts = "/posts/:contentbasename/"
  pages = "/:contentbasename:/"
